*------------------------------------------------------------*;
* Computed Code;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
* TRANSFORM: GiftAvg36 , log(GiftAvg36 + 1);
*------------------------------------------------------------*;
label LOG_GiftAvg36 = 'Transformed: Gift Amount Average 36 Months';
if GiftAvg36 eq . then LOG_GiftAvg36 = .;
else do;
if GiftAvg36 + 1 > 0 then LOG_GiftAvg36 = log(GiftAvg36 + 1);
else LOG_GiftAvg36 = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: GiftAvgAll , log(GiftAvgAll + 1);
*------------------------------------------------------------*;
label LOG_GiftAvgAll = 'Transformed: Gift Amount Average All Months';
if GiftAvgAll eq . then LOG_GiftAvgAll = .;
else do;
if GiftAvgAll + 1 > 0 then LOG_GiftAvgAll = log(GiftAvgAll + 1);
else LOG_GiftAvgAll = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: GiftAvgCard36 , log(GiftAvgCard36 + 1);
*------------------------------------------------------------*;
label LOG_GiftAvgCard36 = 'Transformed: Gift Amount Average Card 36 Months';
if GiftAvgCard36 eq . then LOG_GiftAvgCard36 = .;
else do;
if GiftAvgCard36 + 1 > 0 then LOG_GiftAvgCard36 = log(GiftAvgCard36 + 1);
else LOG_GiftAvgCard36 = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: GiftAvgLast , log(GiftAvgLast + 1);
*------------------------------------------------------------*;
label LOG_GiftAvgLast = 'Transformed: Gift Amount Last';
if GiftAvgLast eq . then LOG_GiftAvgLast = .;
else do;
if GiftAvgLast + 1 > 0 then LOG_GiftAvgLast = log(GiftAvgLast + 1);
else LOG_GiftAvgLast = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: GiftCnt36 , log(GiftCnt36 + 1);
*------------------------------------------------------------*;
label LOG_GiftCnt36 = 'Transformed: Gift Count 36 Months';
if GiftCnt36 eq . then LOG_GiftCnt36 = .;
else do;
if GiftCnt36 + 1 > 0 then LOG_GiftCnt36 = log(GiftCnt36 + 1);
else LOG_GiftCnt36 = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: GiftCntAll , log(GiftCntAll + 1);
*------------------------------------------------------------*;
label LOG_GiftCntAll = 'Transformed: Gift Count All Months';
if GiftCntAll eq . then LOG_GiftCntAll = .;
else do;
if GiftCntAll + 1 > 0 then LOG_GiftCntAll = log(GiftCntAll + 1);
else LOG_GiftCntAll = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: GiftCntCard36 , log(GiftCntCard36 + 1);
*------------------------------------------------------------*;
label LOG_GiftCntCard36 = 'Transformed: Gift Count Card 36 Months';
if GiftCntCard36 eq . then LOG_GiftCntCard36 = .;
else do;
if GiftCntCard36 + 1 > 0 then LOG_GiftCntCard36 = log(GiftCntCard36 + 1);
else LOG_GiftCntCard36 = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: GiftCntCardAll , log(GiftCntCardAll + 1);
*------------------------------------------------------------*;
label LOG_GiftCntCardAll = 'Transformed: Gift Count Card All Months';
if GiftCntCardAll eq . then LOG_GiftCntCardAll = .;
else do;
if GiftCntCardAll + 1 > 0 then LOG_GiftCntCardAll = log(GiftCntCardAll + 1);
else LOG_GiftCntCardAll = .;
end;
